# Generated by Django 5.1.2 on 2024-11-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someproject',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='someproject',
            name='image',
            field=models.ImageField(upload_to='media/projects/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='someproject',
            name='title',
            field=models.CharField(max_length=155, verbose_name="Ім'я проекту"),
        ),
    ]
