# Generated by Django 5.1.2 on 2024-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_someproject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someproject',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Фото'),
        ),
    ]
