# Generated by Django 5.1.2 on 2024-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_someproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someproject',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Фото'),
        ),
    ]
