# Generated by Django 5.1.2 on 2024-11-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_someproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name="Ім'я проекту")),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='projects/image', verbose_name='Фото')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='someproject',
            name='title',
            field=models.CharField(max_length=155, verbose_name="Ім'я оновлення"),
        ),
    ]
